### ISSUE TITLE
Edit already existed highlights 

### ISSUE THREAD

**Issue by Victor1266** [jsonMartin/readwise-mirror#15]
For some reason if I edit highlights in the readwise this change is not syncing.
Only when new highlights added the sync is updating the note

Is it possible to update the note when the edit for already created highlights happend?

**Comment by jsonMartin** [comment]
Hey @Victor1266 , I just gave this a test, and am able to get edited highlights to sync when modified via Kindle, but NOT when edited via Readwise's app - this appears to be a limitation of Readwise's syncing mechanism (see below). 

You're right that this does NOT automatically sync when editing a highlight note via the Readwise app, versus directly via Kindle. This is likely because editing notes in the Readwise App overwrites changes from the Kindle - if you check your Kindle after syncing both Readwise & Kindle, you'll see that your edited notes via the Readwise app won't show up back inside of the Kindle. For the same reason, edits within the Readwise app won't trigger a sync to Obsidian. 

If you're editing via the Readwise app and aren't seeing your change come over, then you can force these notes to update by selecting the "**_Download entire Readwise library (force)_**" command. Or, these changes should also sync properly the next time you have new content from Readwise, such as a new highlight or book.

If you want this to work seamlessly, then edit your notes via the source (Kindle device/app) instead of the Readwise app. Doing it this way will cause a sync to be triggered via Readwise's API.

Here's the steps I took to test: 

1. Edit an already existing note within Kindle app to change text
2. Manually Sync Kindle to ensure the newest data available for Readwise
3. Open Readwise App and manually sync highlights (On Android app, select Add Highlights tab -> Sync button under **Connect & Sync**)
    - Wait for Sync successful message
    - Might say "No New Highlights" found (since you're not adding any new highlights just editing existing highlights), but if you check the highlight under the book, the new note should show up within the app
4. Now that you can see the updated highlight note text within Readwise's app, go to Obsidian and choose "Sync new highlights" command (Ctrl/Cmd P)
5. You should now see your new note has synced to the existing highlight.
