### ISSUE TITLE
Format for highlights is substantially different from the Readwise manual markdown export

### ISSUE THREAD

**Issue by thomasvs** [jsonMartin/readwise-mirror#9]
I just realized that the markdown this plugin exports is substantially different from the Readwise export.

In particular:
* It does not preserve the interpretation of heading tags (.h1, .h2, ... as per https://blog.readwise.io/add-chapters-to-highlights/ )
* It doesn't properly nest highlights under those headings
* It doesn't format as a bullet list
* It adds a lot more whitespace

For example, here is a snippet of the export I get from Readwise:

### Highlights

- # INTRODUCTION
- With Positive Intelligence you can both measure and significantly improve the percentage of time that your mind is serving you rather than sabotaging you. ([Location 117](https://readwise.io/to_kindle?action=open&asin=B007R0IQ70&location=117))
- # PART I WHAT IS POSITIVE INTELLIGENCE AND PQ?
- ## CHAPTER 1 POSITIVE INTELLIGENCE AND PQ
- Using the principles of Positive Intelligence, we devised a core question to reframe and redirect the team’s perspective and redirect its efforts: “What do we need to do so that within three years we can say this current crisis was the best thing that could have happened to our company?” ([Location 139](https://readwise.io/to_kindle?action=open&asin=B007R0IQ70&location=139))
- When I checked in with Frank recently, he reported that he valued his increased sense of peace and happiness even more highly than his impressive professional and financial gains. ([Location 150](https://readwise.io/to_kindle?action=open&asin=B007R0IQ70&location=150))

Here is the start of the snippet I get from this plugin:

# Highlights 
INTRODUCTION ([102](https://readwise.io/to_kindle?action=open&asin=B007R0IQ70&location=102)) %% Color: yellow %% ^203951410

**Note: .h1**

---

PART I WHAT IS POSITIVE INTELLIGENCE AND PQ? ([128](https://readwise.io/to_kindle?action=open&asin=B007R0IQ70&location=128)) %% Color: yellow %% ^203951411

**Note: .h1**

---

CHAPTER 1 POSITIVE INTELLIGENCE AND PQ ([130](https://readwise.io/to_kindle?action=open&asin=B007R0IQ70&location=130)) %% Color: yellow %% ^203951412

**Note: .h2**

---

“What do we need to do so that within three years we can say this current crisis was the best thing that could have happened to our company?” ([2191](https://readwise.io/to_kindle?action=open&asin=B007R0IQ70&location=2191)) %% Color: yellow %% ^203951413

---

PQ stands for Positive Intelligence Quotient. Your PQ is your Positive Intelligence score, expressed as a percentage, ranging from 0 to 100. In effect, your PQ is the percentage of time your mind is acting as your friend rather than as your enemy; or, in other words, it is the percentage of time your mind is serving you versus sabotaging you. ([161](https://readwise.io/to_kindle?action=open&asin=B007R0IQ70&location=161)) %% Color: yellow %% ^203951415

---

**Comment by jsonMartin** [comment]
Hi @thomasvs , this plugin wasn't necessarily intended to provide an exact 1:1 export compared to the Markdown format from Readwise; their export feature has many other capabilities such as templating engine. Readwise's API returns plain unformatted text per highlight, not a formatted document - their Markdown export format is only directly available through their website. 

FYI, I also haven't used Heading Tags myself, so did not add any custom code to support this. 

However, customization of highlight documents will be possible when templating engine is added in a future release, please track this issue here for updates: https://github.com/jsonMartin/readwise-mirror/issues/11

Also, Readwise has just released their official Obsidian plugin last week, so if controlling the formatting of the notes is more important to your needs than the mirror syncing functionality this plugin provides, you might want to consider using their plugin instead: https://help.readwise.io/article/125-how-does-the-readwise-to-obsidian-export-integration-work
